serenity.project.name=SWAG LABS
serenity.test.root=oren.example
webdriver.driver=chrome
webdriver.autodownload=true
serenity.browser.maximized=false
serenity.use.unique.browser=false
serenity.restart.browser.each.scenario=true
headless.mode=true
webdriver.base.url=http://frontend:5173
chrome.switches=--no-sandbox,--disable-dev-shm-usage,--disable-gpu
webdriver.autodownload=false
webdriver.chrome.driver=/usr/local/bin/chromedriver